import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, getLocale } from "next-intl/server";
import Sidebar from "@/components/layout/Sidebar/SidebarsLayout";
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Rickson Portifolio",
  description: "Generated by create next app",
  icons: "/favicon.svg"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  console.log(locale);
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Sidebar>
            <main className="min-h-dvh px-5 md:px-8 py-8 overflow-hidden flex flex-col gap-8">
              {children}
            </main>
          </Sidebar>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
